# Generated by Django 2.2.4 on 2019-09-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField('Page', 'slug', models.CharField(max_length=200)),
    ]
